language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: Am1OeWzektzwRtTkm8T4fBY5Vmek0XQmnQ1pN3Ul7ThOSwj5J+q1qYIgYvXdfbbKJqQLZp8TYjh1XP0pvkgUdkAs190wQtMPnusxP63aYIaONvNZOXqMVXxh9SnDWx1ca0RrWN3KHHyABdyOHasQuGaCCupN896+Wmu+Bgn1f8vLB/zr8FX2Wm2mfB6C76SOu9dpeqSDJk4ska6XWOLgLOEvam0uYNVcTbLjuI7L+29u8QkEVlezHtbzdXDECa160cy9Y/TDPpyCed/u9Oj/3MxDo3fgdzF4EPiBnkP2MVJFovOMhALwn91ljDmrGlNhjLNfCgeOqF+tswzYob4c49OG/EG1krk0+w2lmdH7FKbGqCmNgv03rG9RsgjdWnu6HtznB9XcYhvsWEGNHA2BaeDK0xzYVFv8WuLrdZzFCGbjgc/XCVTHs0p+G1KMtNhbI9CFC4rWhrGFPkZTQ87A5jytl558P6SOWLPJXv/f5sJtrjqsaSH5KLAQT5NhJajg55rBabiFEWWyqvuroCuqB33LqZJJaX85RAJ0lcH+AdTe0YEQpchTt8zkdic6ilj4dTpdBMbOry8XCKrT2wzY25NGMgTX3emuwNxo6gHMfzPo5bkcEONetle0VQirb2Xwk2nEzHmOuSNvHqwC42qacNDkopXCmVvLjUii2iAWDck=
